## Particle in Cell method for the one-dimensional two-counterstreaming plasma

In [105]:
import numpy as np
import matplotlib as plt
import scipy.linalg as la

Define the normalized/unitless constants

In [44]:
class Setup:
    def __init__(self, l, ns, nc, np, dt):
        self.L = l
        self.numSteps = ns
        self.numCells = nc
        self.numParticles = np
        self.cellSize = l/nc
        self.timeStep = dt

Setting up the arrays that will store the charge density, potential, and electric field in each cell; as well as arrays for storing particle positions and velocities. Assigning initial values for these quantities.

In [130]:
setupObj = Setup(1,3,5,100, 0.5)
potentials = np.zeros((setupObj.numSteps, setupObj.numCells))
elfields = np.zeros((setupObj.numSteps, setupObj.numCells))
chargedensities = np.zeros((setupObj.numSteps, setupObj.numCells))
positions = np.zeros((setupObj.numSteps, setupObj.numParticles))
velocities = np.zeros((setupObj.numSteps, setupObj.numParticles))
initStreamVelocity = 1.
velocities[0] = ((np.arange(setupObj.numParticles)%2)*2-1)*initStreamVelocity

totalMomentum = np.zeros(setupObj.numSteps)
totalKinEnergy = np.zeros(setupObj.numSteps)
totalPotEnergy = np.zeros(setupObj.numSteps)
totalEnergy = np.zeros(setupObj.numSteps)

Main program loop (runs once for each simulation cycle, numSteps times)

In [131]:
for it in range(1):
    # Assign charge densities to cells (using nearest-neighbour approach)
    np.add.at(chargedensities[it], np.array(np.round(positions[it]/setupObj.cellSize), dtype=int), 1)
    chargedensities[it] /= setupObj.cellSize
    
    # Calculate the potentials
    potSolverMatrix = (np.diag(np.full(setupObj.numCells,-2.))
                       + np.diag(np.ones(setupObj.numCells-1),1)
                       + np.diag(np.ones(setupObj.numCells-1),-1))                
#     potSolverMatrix[0,-1]=1
#     potSolverMatrix[-1,0]=1
    potentials[it] = la.solve(potSolverMatrix, -chargedensities[it]*(setupObj.cellSize)**2)
    
    # Calculate the electric fields
    

[16.66666667 13.33333333 10.          6.66666667  3.33333333]


In [78]:
s = np.zeros(10)
print(s)
a = np.array([2,3,2,4,3])

np.add.at(s,a,1)
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 2. 1. 0. 0. 0. 0. 0.]


In [83]:
np.rint(1.2)

1.0